
project_id = "kkdldvrceqdcgclnvixt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
shadow_database_schema = "shadow"
shadow_database_in_container = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

# Edge Functions
[functions]
[functions.products]
verify_jwt = false

[functions.product-detail]
verify_jwt = false

[functions.filters]
verify_jwt = false

[functions.navigation]
verify_jwt = false
