
project_id = "kkdldvrceqdcgclnvixt"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[storage]
file_size_limit = "50MiB"
